# vim mode
bindkey -v

setopt correct
setopt extended_glob
setopt interactive_comments
setopt pushd_ignore_dups
setopt numeric_glob_sort
setopt no_list_beep

# Special Functions
typeset -ag chpwd_functions
typeset -ag periodic_functions
typeset -ag precmd_functions
typeset -ag preexec_functions

# znamedir
function _precmd_znamedir_refresh { znamedir refresh }
precmd_functions+=_precmd_znamedir_refresh

# Pipe and Redirection settings
setopt noclobber
setopt multios

# Completion
autoload -U compinit
compinit

# History settings
setopt hist_allow_clobber
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_no_store
setopt inc_append_history
setopt share_history
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=$ZDOTDIR/.history

# Other imports
source-default aliases
source-default bindings
