# vim mode
bindkey -v

setopt extended_glob
setopt interactive_comments
setopt pushd_ignore_dups
setopt numeric_glob_sort
setopt no_list_beep
setopt transient_rprompt

# Special Functions
typeset -ag chpwd_functions
typeset -ag periodic_functions
typeset -ag precmd_functions
typeset -ag preexec_functions

# znamedir
function _precmd_znamedir_refresh { znamedir refresh }
precmd_functions+=_precmd_znamedir_refresh

# keymap reset
function _precmd_prompt_update { __prompt_update_from_keymap main }
precmd_functions+=_precmd_prompt_update

# Pipe and Redirection settings
setopt noclobber
setopt multios

# History settings
setopt hist_allow_clobber
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_no_store
setopt inc_append_history
setopt share_history
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=$ZDOTDIR/.history

# Other imports
source-default aliases
source-default bindings
source-default completions
